### ISSUE TITLE
Validation Errors

### ISSUE THREAD

**Issue by kevski** [centrify/saml-sdk#1]
Given the example value-response & value-response2 files don't actually validate against the saml response schema, does that imply that the sample code does not work, or that the certify library does not do xml schema validation?

When testing on another system I was getting errors:
The content of element 'saml2:AuthnContext' is not complete. One of '{"urn:oasis:names:tc:SAML:2.0:assertion":AuthnContextClassRef, "urn:oasis:names:tc:SAML:2.0:assertion":AuthnContextDecl, "urn:oasis:names:tc:SAML:2.0:assertion":AuthnContextDeclRef}' is expected.

**Comment by nick-gamb** [comment]
Kevin,

This is meant to be a very basic example to get started with for our customers who do not know where to start with SAML. This is not meant to be a full SAML SP solution right out of the box. The code sets up a basic ACS to receive an assertion and a basic redirect to IDP for SP initiated. When the ACS receives the assertion, the code will verify the signature using a stored cert. That is the full scope of this code at this time. At this point the code could be expanded upon to do schema validation, check entity id, and implement other aspects of SAML compliancy. However, I felt that adding too much would confuse developers who are new to SAML. This is meant to be a jumping off point. Please let me know if I can assist further.

Thank you,

Nick Gamb
Product Manager and Developer Advocate
Centrify Corporation

Mobile: (208) 697-7095
nick.gamb@centrify.com<mailto:nick.gamb@centrify.com>

Identify. Unify. Centrify.
Centrify delivers Unified Identity Services across data center, cloud and mobile: One single login for users. One unified identity infrastructure for IT. www.centrify.com<http://www.centrify.com/default.asp?ls=011-002-email-sig>
